// This is part of a version currently in development and may be changed at any time.

// Tags
var Item = {name: "Item", max: [25, 25, 20, 20, 20], line: true},
Stat = {name: "Stat", max: [5, 5, 5, 5, 5], line: true},
Advancement = {name: "Advancement", max: [8, 8, 8, 8, 8], line: true},
Action = {name: "Action", max: [20, 20, 20, 20, 20], line: true},
Build = {name: "Build", max: [20, 20, 20, 20, 20], line: true},
// note, that on lower difficulties, RareBiome means "Specific Biome"
RareBiome = {name: "RareBiome", max: [0, 2, 3, 4, 6], line: true},
Ocean = {name: "Ocean", max: [5, 5, 5, 5, 5], line: true},
Village = {name: "Village", max: [0, 1, 2, 3, 4], line: true},
Colour = {name: "Colour", max: [2, 2, 2, 2, 2], line: true},
Never = {name: "Never", max: [1, 1, 1, 1, 1], line: false},
Combat = {name: "Combat", max: [5, 10, 20, 20, 20], line: true},
Overworld = {name: "Overworld", max: [25, 25, 24, 21, 18], line: true},
Nether = {name: "Nether", max: [0, 2, 5, 10, 15], line: true},
End = {name: "End", max: [0, 0, 0, 1, 5], line: true},
Finish = {name: "Finish", max: [1, 1, 1, 1, 1], line: true},
Netherite = {name: "Netherite", max: [0, 0, 0, 1, 3], line: true};
Name = {name: "Name", max: [2, 2, 2, 2, 2], line: true};

var bingoList_v5 = [

// Very Easy (0)
[
	{name: "Die.", tags: [Action]},
	{name: "Get 64 of anything.", tags: [Item]},
	{name: "Eat something.", tags: [Action]},
	{name: "Open a door.", tags: [Action]},
	{name: "Have at least 6 mobs following you.", tags: [Combat]},
	{name: "Kill a mob with a pumpkin on your head.", tags: [Combat]},
	{name: "Place 6 lightning rods all facing different directions.", tags: [Build]},
	{name: "Make a bee enter a boat.", tags: [Action]},
	{name: "Make an armor stand go up 3 blocks without breaking it.", tags: [Action]},
	{name: "Destroy a gravity affected block by making it fall on something.", tags: [Action]},
	{name: "Watch or make an enderman teleport.", tags: [Action]},
	{name: "Build a 32 block tall tower.", tags: [Build]},
	{name: "Make a water source block turn into a solid.", tags: [Action]},
	{name: "Kill a mob using block suffocation.", antisynergy: ["KillFallingBlock"], tags: [Combat]},
	{name: "Make a dispenser or dropper trigger itself.", tags: [Build]},
	{name: "Witness another mob hit a skeleton.", tags: [Action, Combat]},
	{name: "Make a creeper's explosion destroy zero blocks.", tags: [Action]},
	{name: "Reach a negative height.", tags: [Action]},
	{name: "Open a naturally spawned chest.", tags: [Action]},
	{name: "Have 0 hunger.", infrequency: 3, tags: [Action]},
	{name: "Kill a mob with fall damage.", infrequency: 2, tags: [Action, Combat]},
	{name: "Kill (4-6) different passive mobs.", tooltiptext:"Check Stats. These are any mobs that cannot hurt you.", infrequency: 5, tags: [Action, Combat, Stat]},
	{name: "Kill any baby.", infrequency: 5, tags: [Action, Combat]},
	{name: "Travel (400-500) meters by Boat total.", tooltiptext: "Check Stats", infrequency: 4, tags: [Stat]},
	{name: "Kill a bat", tags: [Combat, Overworld]},
	{name: "\'Best Friends Forever\' Advancement", tags: [Advancement]},
	{name: "\'The Parrots and the Bats\' Advancement", antisynergy: ["BreedAnimals"], tags: [Advancement]},
	{name: "\'Sweet Dreams\' Advancement", tags: [Advancement]},
	{name: "\'Stone Age\' Advancement", tags: [Advancement]},
	{name: "\'Suit Up\' Advancement", reactant: ["WearArmour"], tags: [Advancement]},
	{name: "\'Isn\'t it Iron Pick?\' Advancement", reactant: ["WearArmour"], tags: [Advancement]},
	{name: "Build a vertical penis with 4 blocks total.", infrequency: 50, tags: [Build]},
	{name: "\'Not Today, Thank you\' Advancement", tags: [Advancement]},
	{name: "(32-64) Cobblestone", tags: [Item, Overworld]},
	{name: "(32-64) Dirt", tags: [Item, Overworld]},
	{name: "(32-64) Oak Wood Planks", antisynergy: ["OakPlanks"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(32-64) Spruce Wood Planks", antisynergy: ["SprucePlanks"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(32-64) Birch Wood Planks", antisynergy: ["BirchPlanks"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(32-64) Dark Oak Wood Planks", antisynergy: ["DarkOakPlanks"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(32-64) Acacia Wood Planks", antisynergy: ["AcaciaPlanks"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(5-15) Oak Logs", antisynergy: ["OakLogs"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(5-15) Spruce Logs", antisynergy: ["SpruceLogs"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(5-15) Birch Logs", antisynergy: ["BirchLogs"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(5-15) Dark Oak Logs", antisynergy: ["DarkOakLogs"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(5-15) Acacia Logs", antisynergy: ["AcaciaLogs"], infrequency: 25, tags: [Item, Overworld]},
	{name: "Redstone", antisynergy: ["Redstone"], infrequency: 2, tags: [Item, Overworld]},
	{name: "Lava Bucket", antisynergy: ["LavaBucket"], reactant: ["UseBuckets"], infrequency: 4, tags: [Item]},
	{name: "Milk Bucket", antisynergy: ["MilkBucket"], reactant: ["UseBuckets"], infrequency: 4, tags: [Item, Overworld]},
	{name: "Water Bucket", antisynergy: ["WaterBucket"], reactant: ["UseBuckets"], infrequency: 4, tags: [Item, Overworld]},
	{name: "Bucket of Fish", antisynergy: ["FishBucket"], reactant: ["UseBuckets"], infrequency: 4, tooltiptext: "Can be any of the types of Fish.", tooltipimg: "Goal Tooltip Images/FishBucket.jpg", tags: [Item, Ocean, Overworld]},
	{name: "(16-32) Andesite", infrequency: 5, tags: [Item, Overworld]},
	{name: "(16-32) Granite", infrequency: 5, tags: [Item, Overworld]},
	{name: "(16-32) Diorite", infrequency: 5, tags: [Item, Overworld]},
	{name: "(16-32) Deepslate", infrequency: 5, tags: [Item, Overworld]},
	{name: "(16-32) Tuff", infrequency: 8, tags: [Item, Overworld]},
	{name: "Iron Block", antisynergy: ["IronBlocks"], infrequency: 2, tags: [Item]},
	{name: "(5-25) Poppies & (5-25) Dandelions", tags: [Item, Overworld]},
	{name: "Level (5-7)", antisynergy: ["Level"], infrequency: 2, tags: [Stat]},
	{name: "(32-64) Leaves", tags: [Item, Overworld]},
	{name: "Build a (2-4)x(2-4)x(2-4) leaf cube", tooltiptext: "You can choose what shall be the width/length/height.", tooltipimg: "Goal Tooltip Images/LeafCube.jpg", tags: [Build, Overworld]},
	{name: "(2-4) Colours of Wool", antisynergy: ["WoolColour"], infrequency: 4, tags: [Item, Colour, Overworld]},
	{name: "(8-16) Snowballs", tags: [Item, RareBiome, Overworld]},
	{name: "(2-4) Different Slabs", antisynergy: ["Slabs"], infrequency: 2, tags: [Item]},
	{name: "(2-4) Different Stairs", antisynergy: ["Stairs"], infrequency: 2, tags: [Item]},
	{name: "Diamond", tags: [Item]},
	{name: "(5-15) Rotten Flesh", antisynergy: ["RotFlesh"], infrequency: 2, tags: [Item]},
	{name: "(10-32) Stone", tooltiptext: "NOT Cobblestone.", tooltipimg: "Goal Tooltip Images/Stone.jpg", antisynergy: ["Stone"], infrequency: 2, reactant: ["UseFurnace"], tags: [Item, Overworld]},
	{name: "(2-5) Bread", antisynergy: ["Bread"], infrequency: 2, tags: [Item, Overworld]},
	{name: "Hay Bale", antisynergy: ["HayBale"], infrequency: 2, tags: [Item, Overworld]},
	{name: "Flower Pot", tags: [Item, Overworld]},
	{name: "(2-10) Feathers", antisynergy: ["Feathers"], infrequency: 2, tags: [Item]},
	{name: "Sleep in a Bed", reactant: ["Sleep"], tags: [Action, Overworld]},
	{name: "(5-15) Charcoal", reactant: ["UseFurnace"], tags: [Item, Overworld]},
	{name: "(5-15) Coal", tags: [Item]},
	{name: "Fishing Rod", tags: [Item]},
	{name: "Apple", antisynergy: ["Apples"], tags: [Item, Overworld]},
	{name: "(32-64) Sticks", antisynergy: ["Sticks"], infrequency: 2, tags: [Item]},
	{name: "(32-64) Kelp", tags: [Item, Ocean, Overworld]},
	{name: "(5-10) Oak Wood", antisynergy: ["OakWood"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(5-10) Spruce Wood", antisynergy: ["SpruceWood"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(5-10) Birch Wood", antisynergy: ["BirchWood"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(5-10) Dark Oak Wood", antisynergy: ["DarkOakWood"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(5-10) Acacia Wood", antisynergy: ["AcaciaWood"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(5-10) Stripped Oak Wood", antisynergy: ["StrippedOakWood"], reactant: ["AxeUse"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(5-10) Stripped Spruce Wood", antisynergy: ["StrippedSpruceWood"], reactant: ["AxeUse"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(5-10) Stripped Birch Wood", antisynergy: ["StrippedBirchWood"], reactant: ["AxeUse"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(5-10) Stripped Dark Oak Wood", antisynergy: ["StrippedDarkOakWood"], reactant: ["AxeUse"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(5-10) Stripped Acacia Wood", antisynergy: ["StrippedAcaciaWood"], reactant: ["AxeUse"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(5-15) Stripped Oak Logs", antisynergy: ["StrippedOakLog"], reactant: ["AxeUse"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(5-15) Stripped Spruce Logs", antisynergy: ["StrippedSpruceLog"], reactant: ["AxeUse"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(5-15) Stripped Birch Logs", antisynergy: ["StrippedBirchLog"], reactant: ["AxeUse"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(5-15) Stripped Dark Oak Logs", antisynergy: ["StrippedDarkOakLog"], reactant: ["AxeUse"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(5-15) Stripped Acacia Logs", antisynergy: ["StrippedAcaciaLog"], reactant: ["AxeUse"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(2-5) Raw Cod", antisynergy: ["RawCod"], infrequency: 2, tags: [Item, Ocean, Overworld]},
	{name: "(2-3) Raw Salmon", antisynergy: ["RawSalmon"], infrequency: 2, tags: [Item, Ocean, Overworld]},
	{name: "(2-3) Different Edible Items", tooltiptext: "Raw and Cooked variants count as one (e.g. Raw Beef and Steak).", tooltipimg: "Goal Tooltip Images/RawAndCooked.jpg", antisynergy: ["EdibleItems"], infrequency: 2, tags: [Item]}, // not tagged with Overworld, because you can get 3 in the Nether
	{name: "Crouch a distance of (50-100) meters", tooltiptext: "Check the 'General' statistics screen!", antisynergy: ["CrouchDistance"], infrequency: 2, tags: [Action, Stat]},
	{name: "Fill all 4 slots of a Campfire", tags: [Action]},
	{name: "Change the colour of text on a Sign", tags: [Action]},
	{name: "Extinguish a Campfire", tags: [Action]},
	{name: "(2-4) Different Gold Items", antisynergy: ["GoldItems"], tooltiptext: "Any item with 'Gold' in its name (yes, even Ingots and Ores).", tags: [Item]},
	{name: "(10-32) Sand", antisynergy: ["Sand"], infrequency: 2, tags: [Item, Overworld]},
	{name: "(5-10) Sandstone", antisynergy: ["Sandstone"], infrequency: 2, tags: [Item, Overworld]},
	{name: "(5-10) Cut Sandstone", antisynergy: ["Sandstone"], infrequency: 2, tags: [Item, Overworld]},
	{name: "(2-5) Paper", antisynergy: ["Paper"], infrequency: 2, tags: [Item, Overworld]},
	{name: "Deplete a Hoe", tooltiptext: "Use a Hoe until it breaks, check the 'Items' statistics screen!", tags: [Action, Stat]},
	{name: "Bounce on a Bed", tags: [Action, Overworld]},
	{name: "Hang up a Painting", antisynergy: ["Painting"], tags: [Action, Overworld]},
	{name: "Fill a Composter", tooltiptext: "Add stuff until you can get Bonemeal out!", tooltipimg: "Goal Tooltip Images/FullComposter.jpg", tags: [Action]},
],

// Easy (1)
[
	{name: "Saddle", tags: [Item]},
	{name: "Place a painting with an animal in it.", tags: [Action]},
	{name: "Make a mob die using an explosion that destroys tiles.", tags: [Combat]},
	{name: "Throw 64 of anything into lava or fire.", tags: [Item, Action]},
	{name: "Destroy a nether portal block.", tags: [Action]},
	{name: "(2-3) different blocks that emit any light, in inventory.", antisynergy: ["EmitLight"], tags: [Item]},
	{name: "Surround at least 2 passive animals in fences or gates.", tags: [Build]},
	{name: "(2-3) different polished blocks", antisynergy: ["PolishedBlocks"], infrequency: 2, tags: [Item]},
	{name: "2 different raw metal blocks.", antisynergy: ["RawMetalBlocks"], infrequency: 2, tags: [Item]},
	{name: "(3-5) Copper Blocks", antisynergy: ["CopperBlocks"], infrequency: 2, tags: [Item]},
	{name: "Watch a mob die on your spyglass.", tags: [Action]},
	{name: "Have 5 mobs at least partially visible in a spyglass at the same time.", tags: [Action]},
	{name: "Do-do-mi. Make 3 note blocks play do-do-mi sequentially, continuously.", tags: [Build, Name]},
	{name: "Dodo mi. Shoot a chicken in the air with a bow or crossbow.", tags: [Action, Combat, Name]},
	{name: "Use a dispenser to light a mob on fire.", tags: [Combat]},
	{name: "Get forced out of bed without any keyboard or mouse input while sleeping.", tags: [Action]},
	{name: "Sargent_SAS. Detonate a TNT in a villager's house.", tags: [Action, Village, Name]},
	{name: "H3rpaD3rp. Make 2 pigs look at you at the same time without holding food.", tags: [Action, Name]},
	{name: "Souvenier! Find and place a naturally spawned block in spawn (use compass) that does not occur in that biome.", tags: [Item, Action]},
	{name: "Attack a piglin.", tags: [Combat, Nether]},
	{name: "Deplete a shear.", tags: [Action]},
	{name: "Sleep next to a sleeping villager.", tags: [Action, Village]},
	{name: "Completely encase a villager's house with any opaque blocks.", tags: [Build, Village]},
	{name: "Use a fishing rod to pull a mob into a 1x1 hole.", tags: [Action]},
	{name: "XsmasherX. Kill a hostile mob with your fists.", tags: [Action, Combat, Name]},
	{name: "Kill a mob that is standing on a dripleaf.", tags: [Action]},
	{name: "Array22. Fill your hotbar with 22 of 9 different items.", tags: [Item, Name]},
	{name: "Mushroomfireman. Surround a red or brown mushroom with fire.", tags: [Action, Name, Nether]},
	{name: "Thevenomous22. Receive or inflict poison in (3-5) different ways.", tags: [Action, Name]},
	{name: "Jungifungi. Collect all of both mushrooms and both nether fungus.", tags: [Item, Name, Nether, RareBiome]},
	{name: "Butterfly1354. Throw butter (a gold ingot) and have it travel at least 13.54 blocks vertically.", tags: [Action, Name]},
	{name: "Liamo3323 afk... Drink or eat (8-9) items in one go without using the keyboard.", tags: [Action, Name]},
	{name: "ARColm. Shoot a mob with a bow with it on the edge of your screen when you fire the arrow.", tags: [Action, Combat, Name]},
	{name: "ChefBaboon. Cook (in furnace) or craft (6-8) different edible items.", tags: [Item, Name]},
	{name: "ARace22. Melee attack a cat or ocelot while sprinting without sneaking or holding fish.", tags: [Action, Name]},
	{name: "Mail3323. Title a book \'3323\' and leave it in a villager's chest.", tags: [Action, Village, Name]},
	{name: "Build an exact copy of a tree next to it.", antisynergy:["BuildATree"], infrequency: 2, tags: [Build]},
	{name: "Froggietime. Kill a frog with a clock.", tags: [Action, RareBiome, Combat, Name]},
	{name: "Kill (4-6) different hostile mobs.", tooltiptext:"Check Stats. These are any mobs that always try to hurt you. No spiders, endermen.", infrequency: 5, tags: [Action, Combat, Stat]},
	{name: "Write a player's name in a book, sign it, and have them die.", tooltiptext: "This can be yourself.", infrequency: 8, tags: [Action]},
	{name: "Light a candle with an arrow", infrequency: 8, tags: [Action, Overworld]},
	{name: "Die to fireworks", antisynergy:["Fireworks"], infrequency: 2, tags: [Action]},
	{name: "Kill (10-15) different mobs", tags: [Action, Combat]},
	{name: "(15-20) Advancements", tags: [Action, Advancement]},
	{name: "Plant sugar cane, cactus or bamboo on a suspicious block", infrequency: 5, tags: [Action, Overworld]},
	{name: "Leave a book with your name in a chest within 10 blocks of the world center (0,~,0).", infrequency: 5, tags: [Action]},
	{name: "Play in a different language (Not English)", tooltiptext: "No Pirate Speak, Anglish, Upside Down!", infrequency: 15, tags: [Never]},
	{name: "Set a Squid or Glow Squid on fire", tags: [Action, Overworld]},
	{name: "Take at least (3-4) hearts of damage by falling on a Hay Bale", infrequency: 4, tags: [Item, Overworld]},
	{name: "Do a lap around a villager house with a minecart without stopping.", infrequency: 2, tags: [Overworld, Action, Village]},
	{name: "Travel (40-50) meters by Minecart total.", tooltiptext: "Check Stats", infrequency: 2, tags: [Stat]},
	{name: "Craft a Trapped Chest", tags: [Action]},
	{name: "Die by Cactus", tags: [Action, Overworld, RareBiome]},
	{name: "Fill an Armor Stand", tags: [Action, Overworld]},
	{name: "Get Mining Fatigue", tags: [Item, Overworld, RareBiome]},
	{name: "Mine (4-6) Different Ores", tags: [Item, Overworld]},
	{name: "Throw an ender pearl from the top of the world.", infrequency: 4, tags: [Action]},
	{name: "Kill a mob with a dispenser", tags: [Action]},
	{name: "Summon the Warden",infrequency: 4, tags: [Action, RareBiome, Overworld]},
	{name: "Break a suspicious gravel/sand", infrequency: 4, tags: [Action, Overworld]},
	{name: "Play (3-5) different instruments from a Note Block", antisynergy: ["NoteBlocks"], infrequency: 4, tags: [Action]},
	{name: "\'Good as New\' Advancement", infrequency: 2, tags: [Advancement, RareBiome]},
	{name: "\'The Cutest Predator\' Advancement", infrequency: 2, tags: [Advancement, RareBiome]},
	{name: "\'Crafters Crafting Crafters\' Advancement", tags: [Advancement]},
	{name: "\'Isn\'t it Scute?\' Advancement", tags: [Advancement, RareBiome, Overworld]},
	{name: "\'Respecting the Remnants\' Advancement", infrequency: 4, tags: [Advancement]},
	{name: "\'Sneak 100\' Advancement", infrequency: 4, tags: [Advancement, RareBiome]},
	{name: "\'The Power of Books\' Advancement", tags: [Advancement, Nether]},
	{name: "\'What a Deal!\' Advancement", tags: [Village, Advancement]},
	{name: "\'Oh Shiny\' Advancement", infrequency: 4, tags: [Advancement, Nether]},
	{name: "\'Cover Me with Diamonds\' Advancement", tags: [Advancement]},
	{name: "64 Wildflowers", tags: [Item]},
	{name: "64 Leaf Litter", tags: [Item]},
	{name: "(4-8) Cactus Flowers", tags: [Item, RareBiome]},
	{name: "(8-16) Firefly Bushes", tags: [Item]},
	{name: "Create any country's flag on a banner, with the correct colors. Except Japan.", tags: [Action]},
	{name: "Use a crafter", tags: [Action]},
	{name: "(16-32) Mud Bricks", tags: [Item]},
	{name: "Fill a Bundle", antisynergy: ["Bundles"], tags: [Item, Overworld]},
	{name: "Trigger a Sculk Sensor", tags: [RareBiome, Action, Overworld]},
	{name: "(2-4) Different Fish", tooltiptext: "Raw and Cooked variants count as one (e.g. Raw Cod and Cooked Cod).", tags: [Item, Overworld]},
	{name: "Grow a Tree in the Nether", tooltiptext: "Huge Crimson/Warped Fungi don't count.", tags: [Action, Nether, Overworld]},
	{name: "(4-7) Colours of Terracotta", reactant: ["UseFurnace"], antisynergy: ["TerracottaColour"], infrequency: 4, tags: [Item, Colour, Overworld]},
	{name: "(2-5) Mushroom Stew", tags: [Item]},
	{name: "Shoot a Button with an Arrow", tags: [Action]},
	{name: "Book and Quill", tags: [Item, Overworld]},
	{name: "(16-32) Flint", tags: [Item]},
	{name: "Eat an entire Cake", reactant: ["EatNonMeat"], tags: [Action, Overworld]},
	{name: "Pumpkin Pie", tags: [Item, Overworld]},
	{name: "Fish a Treasure and a Junk item", tooltiptext: "Treasure: Bow, Enchanted Book, Name Tag, Nautilus Shell, Saddle. Junk: Lily Pad, Bowl, Leather, Boots, Rotten Flesh, Stick, Water Bottle, Bone, Ink Sac, Tripwire Hook", reactant: ["Fishing"], tags: [Action, Overworld]},
	{name: "(16-64) Coarse Dirt", tags: [Item, Overworld]},
	{name: "(2-3) Clocks", tags: [Item, Overworld]},
	{name: "(2-4) Iron Blocks", antisynergy: ["IronBlocks"], infrequency: 2, tags: [Item]},
	{name: "Gold Block", antisynergy: ["GoldBlocks"], infrequency: 2, tags: [Item]},
	{name: "Golden Apple", tags: [Item]},
	{name: "(2-4) Bookshelves", tags: [Item, Overworld]},
	{name: "Never use Shields", tooltiptext: "You can use Shields in crafting, but cannot use them for blocking", tags: [Never]},
	{name: "Jukebox", tags: [Item]},
	{name: "Build a 3x3x3 Glass cube and fill the middle with Lava", tags: [Build, Overworld]},
	{name: "(16-32) Mossy Cobblestone", tags: [Item, Overworld]}, // not RareBiome, because can be found in a Plains Village
	{name: "(5-15) Cacti", tags: [Item, RareBiome, Overworld]},
	{name: "(2-3) TNT", tags: [Item, Overworld]},
	{name: "Level (8-15)", antisynergy: ["Level"], infrequency: 2, tags: [Stat]},
	{name: "Create a Snow Golem", tags: [Action, RareBiome, Overworld]},
	{name: "(5-15) Ink Sacs", antisynergy: ["InkSacs"], infrequency: 2, tags: [Item, Overworld]},
	{name: "(6-10) Bread", antisynergy: ["Bread"], infrequency: 2, tags: [Item, Overworld]},
	{name: "(2-3) Hay Bales", antisynergy: ["HayBale"], infrequency: 2, tags: [Item, Overworld]},
	{name: "(5-8) Colours of Wool", antisynergy: ["WoolColour"], infrequency: 4, tags: [Item, Colour, Overworld]},
	{name: "Piston", tags: [Item, Overworld]},
	{name: "Full Iron Armour", infrequency: 3, tags: [Item]},
	{name: "Full Leather Armour", infrequency: 3, tags: [Item]},
	{name: "Fill a Cauldron with Water", tags: [Overworld]},
	{name: "Complete a Map", antisynergy: ["CompleteMap"], tags: [Action, Overworld]},
	{name: "(5-10) Soul Sand", tags: [Item, Nether]},
	{name: "(5-10) Soul Soil", tags: [Item, Nether]},
	{name: "(5-10) Pumpkins", tags: [Item, Overworld]},
	{name: "(2-5) Carved Pumpkins", tags: [Item, Overworld]},
	{name: "(10-30) Vines", tags: [Item, RareBiome, Overworld]},
	{name: "(5-7) Different Slabs", antisynergy: ["Slabs"], infrequency: 2, tags: [Item]},
	{name: "Wooden, Stone, Gold, Iron and Diamond Sword", infrequency: 2, antisynergy: ["EverySword"], tags: [Item]},
	{name: "Wooden, Stone, Gold, Iron and Diamond Pickaxe", infrequency: 2, antisynergy: ["EveryPickaxe"], tags: [Item]},
	{name: "(8-16) Brick Blocks", reactant: ["UseFurnace"], tags: [Item, Overworld]},
	{name: "(16-32) Nether Brick Blocks", reactant: ["UseFurnace"], tags: [Item, Nether]},
	{name: "(16-32) Arrows", tags: [Item]},
	{name: "(Try to) Sleep in the Nether", tags: [Action, Nether, Overworld]},
	{name: "Fermented Spider Eye", tags: [Item, Overworld]},
	{name: "(5-7) Different Stairs", antisynergy: ["Stairs"], infrequency: 2, tags: [Item]},
	{name: "(2-3) Ender Pearls", antisynergy: ["EnderPearl"], infrequency: 2, tags: [Item]},
	{name: "(4-8) Chicken Eggs", tags: [Item]},
	{name: "Hang up 3 Different 4x4 Paintings", antisynergy: ["Painting"], tags: [Action, Overworld]},
	{name: "(5-10) Bone Blocks", tags: [Item]},
	{name: "2 Creepers in the same Boat", tooltiptext: "The 2 Creepers must be in the same boat at the same time.", tooltipimg: "Goal Tooltip Images/2creepers1boat.jpg", tags: [Action, Combat, Overworld]},
	{name: "(2-3) Different Coloured Shields", tags: [Item, Colour, Overworld]},
	{name: "Dead Bush", tags: [Item, RareBiome, Overworld]},
	{name: "(15-32) Short Grass", tags: [Item, Overworld]},
	{name: "Cyan Dye", infrequency: 10, tags: [Item, Overworld]},
	{name: "Magenta Dye", infrequency: 10, tags: [Item, Overworld]},
	{name: "Red Dye", infrequency: 10, tags: [Item, Overworld]},
	{name: "Orange Dye", infrequency: 10, tags: [Item, Overworld]},
	{name: "Yellow Dye", infrequency: 10, tags: [Item, Overworld]},
	{name: "Green Dye", reactant: ["UseFurnace"], infrequency: 10, tags: [Item, RareBiome, Overworld]},
	{name: "Pink Dye", infrequency: 10, tags: [Item, Overworld]},
	{name: "Purple Dye", infrequency: 10, tags: [Item, Overworld]},
	{name: "Lime Dye", infrequency: 10, tags: [Item, Overworld]},
	{name: "Grow a Huge Mushroom", tags: [Action]},
	{name: "Water, Lava and Milk Bucket", antisynergy: ["BucketTypes", "WaterBucket", "LavaBucket", "MilkBucket"], reactant: ["UseBuckets"], tags: [Item, Overworld]},
	{name: "(5-7) Different Flowers", antisynergy: ["Flowers"], infrequency: 2, tags: [Item, Overworld]},
	{name: "(3-6) Colours of Concrete", antisynergy: ["ConcreteColour"], infrequency: 4, tags: [Item, Colour, Overworld]},
	{name: "(3-6) Colours of Glazed Terracotta", reactant: ["UseFurnace"], antisynergy: ["GlazedColour"], infrequency: 4, tags: [Item, Colour, Overworld]},
	{name: "Place (3-6) colours of Beds next to each other", antisynergy: ["BedColour"], infrequency: 4, tags: [Build, Colour, Overworld]},
	{name: "Finish where you spawned using a Compass", tooltiptext: "Be stood close enough to spin your compass within a couple blocks at the end of the game.", tooltipimg: "Goal Tooltip Images/Compass.jpg", tags: [Action, Overworld, Finish]},
	{name: "(32-48) Stone", tooltiptext: "NOT Cobblestone.", tooltipimg: "Goal Tooltip Images/Stone.jpg", antisynergy: ["Stone"], infrequency: 2, reactant: ["UseFurnace"], tags: [Item, Overworld]},
	{name: "Kill (4-8) passive mobs with only fire", tooltiptext: "Don't hurt the passive mob any other way, only with Fire.", reactant: ["Pacifist"], tags: [Action, Combat]},
	{name: "Kill a Creeper with only fire", reactant: ["Pacifist"], tags: [Action, Combat, Overworld]},
	{name: "(32-64) Iron Nuggets", tags: [Item]},
	{name: "(32-64) Gold Nuggets", tags: [Item]},
	{name: "(16-32) Rotten Flesh", antisynergy: ["RotFlesh"], infrequency: 2, tags: [Item]},
	{name: "(16-64) Redstone", antisynergy: ["Redstone"], infrequency: 2, tags: [Item, Overworld]},
	{name: "Golden Carrot", tags: [Item]},
	{name: "Rotten Flesh, Spider Eye, Bone, Gunpowder and Ender Pearl", tags: [Item, Overworld]},
	{name: "(16-32) Feathers", antisynergy: ["Feathers"], infrequency: 2, tags: [Item]},
	{name: "(2-10) Lily Pads", tags: [Item, RareBiome, Overworld]},
	{name: "(65-128) Sticks", antisynergy: ["Sticks"], infrequency: 2, tags: [Item]},
	{name: "Wear 4 different colour Leather Armour at the same time", reactant: ["WearArmour"], tags: [Item, Colour, Overworld]},
	{name: "(15-32) Seagrass", antisynergy: ["Seagrass"], infrequency: 2, tags: [Item, Ocean, Overworld]},
	{name: "(65-128) Oak Wood Planks", antisynergy: ["OakPlanks"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(65-128) Spruce Wood Planks", antisynergy: ["SprucePlanks"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(65-128) Birch Wood Planks", antisynergy: ["BirchPlanks"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(65-128) Dark Oak Wood Planks", antisynergy: ["DarkOakPlanks"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(65-128) Acacia Wood Planks", antisynergy: ["AcaciaPlanks"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(16-32) Oak Logs", antisynergy: ["OakLogs"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(16-32) Spruce Logs", antisynergy: ["SpruceLogs"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(16-32) Birch Logs", antisynergy: ["BirchLogs"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(16-32) Dark Oak Logs", antisynergy: ["DarkOakLogs"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(16-32) Acacia Logs", antisynergy: ["AcaciaLogs"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(11-20) Oak Wood", antisynergy: ["OakWood"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(11-20) Spruce Wood", antisynergy: ["SpruceWood"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(11-20) Birch Wood", antisynergy: ["BirchWood"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(11-20) Dark Oak Wood", antisynergy: ["DarkOakWood"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(11-20) Acacia Wood", antisynergy: ["AcaciaWood"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(11-20) Stripped Oak Wood", antisynergy: ["StrippedOakWood"], reactant: ["AxeUse"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(11-20) Stripped Spruce Wood", antisynergy: ["StrippedSpruceWood"], reactant: ["AxeUse"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(11-20) Stripped Birch Wood", antisynergy: ["StrippedBirchWood"], reactant: ["AxeUse"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(11-20) Stripped Dark Oak Wood", antisynergy: ["StrippedDarkOakWood"], reactant: ["AxeUse"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(11-20) Stripped Acacia Wood", antisynergy: ["StrippedAcaciaWood"], reactant: ["AxeUse"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(16-32) Stripped Oak Logs", antisynergy: ["StrippedOakLog"], reactant: ["AxeUse"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(16-32) Stripped Spruce Logs", antisynergy: ["StrippedSpruceLog"], reactant: ["AxeUse"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(16-32) Stripped Birch Logs", antisynergy: ["StrippedBirchLog"], reactant: ["AxeUse"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(16-32) Stripped Dark Oak Logs", antisynergy: ["StrippedDarkOakLog"], reactant: ["AxeUse"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(16-32) Stripped Acacia Logs", antisynergy: ["StrippedAcaciaLog"], reactant: ["AxeUse"], infrequency: 25, tags: [Item, Overworld]},
	{name: "Tropical Fish", tags: [Item, Ocean, Overworld]},
	{name: "Pufferfish", tags: [Item, Ocean, Overworld]},
	{name: "(6-15) Raw Cod", antisynergy: ["RawCod"], infrequency: 2, tags: [Item, Ocean, Overworld]},
	{name: "(4-7) Raw Salmon", antisynergy: ["RawSalmon"], infrequency: 2, tags: [Item, Ocean, Overworld]},
	{name: "Get a Fish into the Nether", reactant: ["Pacifist"], tags: [Nether, Action, Overworld]},
	{name: "(5-9) Dried Kelp Blocks", antisynergy: ["KelpBlocks"], tags: [Item, Ocean, Overworld]},
	{name: "Drown a Zombie", tags: [Action, Combat, Overworld]},
	{name: "(2-5) Gunpowder", antisynergy: ["Gunpowder"], infrequency: 2, tags: [Item]},
	{name: "(2-5) Spider Eyes", antisynergy: ["SpiderEye"], infrequency: 2, tags: [Item, Overworld]},
	{name: "Breed (2-4) sets of mobs", tooltiptext: "Check the 'General' statistics screen!", antisynergy: ["BreedAnimals"], infrequency: 2, tags: [Action, Stat]},
	{name: "Crouch a distance of (100-200) meters", tooltiptext: "Check the 'General' statistics screen!", antisynergy: ["CrouchDistance"], infrequency: 2, tags: [Action, Stat]},
	{name: "Never use Third Person (F5)", tags: [Never]},
	{name: "Ring a Bell from 10 blocks away", tags: [Action, Village, Overworld]},
	{name: "Repair an Item with a Grindstone", tags: [Action]},
	{name: "(2-6) Sweet Berries", tags: [Item, Overworld, RareBiome]},
	{name: "Banner Pattern", tooltiptext: "Any kind of Banner Pattern.", tags: [Item, Overworld]},
	{name: "Drink a Suspicious Stew", reactant: ["EatNonMeat"], tags: [Item, Overworld]},
	{name: "Give a Fox a Sword", tags: [Action, Overworld, RareBiome]},
	{name: "Honey Bottle", antisynergy: ["Honey"], infrequency: 2, tags: [Item, Overworld]},
	{name: "3 Honeycombs", antisynergy: ["Honeycomb"], infrequency: 2, tags: [Item, Overworld]},
	{name: "(2-6) Basalt", tags: [Item, Nether]},
	{name: "(2-6) Blackstone", tags: [Item, Nether]},
	{name: "Fill all 4 slots of a Soul Campfire with Porkchops", reactant: ["Pacifist"], tags: [Action, Nether, Combat]},
	{name: "Soul Lantern", tags: [Item, Nether]},
	{name: "Open a Door with a Target Block from 10 blocks away", tooltiptext: "YOU have to be 10 blocks away, not the Target Block from the Door.", tooltipimg: "Goal Tooltip Images/TargetAndDoor.jpg",  tags: [Action, Overworld]},
	{name: "Carrot on a Stick", tags: [Item]},
	{name: "Barter with a Piglin", tags: [Action, Nether]},
	{name: "Become Nauseous", reactant: ["EatMeat"], tags: [Item, Ocean, Overworld]},
	{name: "Enchanted item", tags: [Item]},
	{name: "Remove an Enchantment with a Grindstone", tags: [Action]},
	{name: "Clean a Pattern off a Banner", tags: [Action, Overworld]},
	{name: "(5-7) Different Gold Items", antisynergy: ["GoldItems"], tooltiptext: "Any item with 'Gold' in its name (yes, even Ingots and Ores).", tags: [Item]},
	{name: "(33-64) Sand", antisynergy: ["Sand"], infrequency: 2, tags: [Item, Overworld]},
	{name: "(11-32) Sandstone", antisynergy: ["Sandstone"], infrequency: 2, tags: [Item, Overworld]},
	{name: "(11-32) Cut Sandstone", antisynergy: ["Sandstone"], infrequency: 2, tags: [Item, Overworld]},
	{name: "(6-15) Paper", antisynergy: ["Paper"], infrequency: 2, tags: [Item, Overworld]},
	{name: "(3-6) Coal Blocks", reactant: ["NeverCoal"], tags: [Item]},
	{name: "(2-5) Apples", antisynergy: ["Apples"], tags: [Item, Overworld]},
	{name: "Tame a Horse", tags: [Action, Overworld]},
	{name: "Hatch a Chicken from an Egg", infrequency:3, tags: [Action, Overworld]},
	{name: "Empty a Cauldron without Buckets or Bottles", tooltiptext: "You can fill the Cauldron with Water however you want, just don't use Buckets or Bottles to empty it.", tags: [Action, Overworld]},
	{name: "Sleep in a Villager's bed", reactant: ["Sleep"], tags: [Action, Village, Overworld]},
	{name: "Set fire to a Villager's House", tags: [Action, Village, Overworld]},
	{name: "Emerald",antisynergy:["Emeralds"], tags: [Item, Overworld]},
],

// Medium (2)
[	
	{name: "Leash a mob to a Hoglin", tags: [Action, Nether]},
	{name: "Obtain a music disc NOT from a creeper.", tags: [Item]},
	{name: "Dried Ghast", tags: [Item, Nether]},
	{name: "Finish with a Tropical Fish in a Bucket", tags: [Item, Ocean, Overworld, RareBiome]},
	{name: "(8-10) Emeralds",antisynergy:["Emeralds"], tags: [Item]},
	{name: "(4-5) different blocks that emit any light, in inventory.", antisynergy: ["EmitLight"], tags: [Item]},
	{name: "(4-5) different polished blocks", antisynergy: ["PolishedBlocks"], infrequency: 2, tags: [Item]},
	{name: "Build an exact copy of a tree next to it using different logs and leaves.", antisynergy:["BuildATree"], infrequency: 2, tags: [Build]},
	{name: "Kill a hostile mob with Powdered Concrete", reactant: ["Pacifist"], antisynergy: ["KillFallingBlock"], infrequency: 2, tags: [Action, Combat]},
	{name: "3 different raw metal blocks.", antisynergy: ["RawMetalBlocks"], infrequency: 2, tags: [Item]},
	{name: "(5-7) Copper Blocks", antisynergy: ["CopperBlocks"], infrequency: 2, tags: [Item]},
	{name: "Watch a wolf dry itself.",antisynergy:["TameWolf"], tags: [Action]},
	{name: "Make a snow golem and have it die by biome temperature.", tags: [Action, RareBiome]},
	{name: "Elsidraws. Build the word \'ELSI\' using at least 10 different fully opaque blocks.",tooltiptext:" All Letters should be 3x5 size.", tags: [Build, Name]},
	{name: "drjulian8. Eat a Golden Apple while you have the Weakness effect.", tags: [Action, Name]},
	{name: "Build an exact copy of a villager's house next to it.", infrequency: 5, tags: [Build, Village]},
	{name: "Kill (2-3) different neutral mobs.", tooltiptext:"Check Stats. These are any mobs that can be passive that can hurt you.", infrequency: 5, tags: [Action, Combat, Stat]},
	{name: "Kill a mob with a Splash Water Bottle", infrequency: 2, tags: [Action, Combat, Nether]},
	{name: "Use a firework to ring a bell", antisynergy:["Fireworks"], infrequency: 2, tags: [Action]},
	{name: "Kill a creeper with fireworks", antisynergy:["Fireworks"], infrequency: 2, tags: [Action, Combat]},
	{name: "Take damage from an armor stand.", infrequency: 2, tags: [Action]},
	{name: "Ride a pig", infrequency: 4, tags: [Item, Overworld]},
	{name: "(7-9) different Bamboo themed items", tooltiptext: "Any item with \'Bamboo\' in its name.", infrequency: 8, tags: [Item, Overworld, RareBiome]},
	{name: "Have (3-5) effects at the same time", infrequency: 4, tags: [Action]},
	{name: "\'Stay Hydrated!\' Advancement", tags: [Advancement, Nether]},
	{name: "\'Heart Transplanter\' Advancement", infrequency: 8, tags: [Advancement, RareBiome]},
	{name: "\'Bullseye\' Advancement", tags: [Advancement]},
	{name: "\'Is it a Balloon?\' Advancement", infrequency: 4, tags: [Advancement, Nether]},
	{name: "\'Wax Off\' Advancement", infrequency: 2, tags: [Advancement]},
	{name: "\'Bukkit Bukkit\' Advancement", infrequency: 16, tags: [Advancement, RareBiome]},
	{name: "\'Smells Interesting\' Advancement", infrequency: 16, tags: [Advancement]},
	{name: "\'Whatever Floats Your Goat!\' Advancement", infrequency: 8, tags: [Advancement, RareBiome]},
	{name: "\'You\'ve Got a Friend in Me\' Advancement", antisynergy: ["BreedAnimals"], tags: [Advancement]},
	{name: "\'Sound of Music\' Advancement", infrequency: 2, tags: [Advancement, RareBiome, Overworld]},
	{name: "\'Careful Restoration\' Advancement", antisynergy: ["DecoratedPots"], infrequency: 8, tags: [Advancement, Overworld]},
	{name: "\'Is it a Bird?\' Advancement", infrequency: 2, tags: [Advancement, RareBiome, Overworld]},
	{name: "\'Country Lode, Take Me Home\' Advancement", infrequency: 4, tags: [Advancement]},
	{name: "\'Not Quite \"Nine\" Lives\' Advancement", infrequency: 4, tags: [Advancement, Nether]},
	{name: "\'Hot Tourist Destinations\' Advancement", infrequency: 4, tags: [Advancement, Nether]},
	{name: "\'Hidden in the Depths\' Advancement", tags: [Advancement, Nether]},
	{name: "\'Enchanter\' Advancement", tags: [Advancement]},
	{name: "\'Those Were the Days\' Advancement", tags: [Advancement, Nether]},
	{name: "\'Into Fire\' Advancement", reactant: ["Pacifist"], tags: [Advancement, Nether]},
	{name: "\'Local Brewery\' Advancement", infrequency: 4, tags: [Advancement, Nether]},
	{name: "Poison a bee.",tooltiptext: "Any way works. Witnessing a poisoned bee counts.", infrequency: 8, tags: [Action, RareBiome]},
	{name: "Kill a Creaking", infrequency: 3, reactant: ["Pacifist"], tags: [Action, RareBiome]},
	{name: "Potion of Oozing", infrequency: 12, reactant: ["Pacifist"], tags: [Item, Nether, Overworld, Combat]},
	{name: "Potion of Infestation", infrequency: 8, reactant: ["Pacifist"], tags: [Item, Nether, Overworld, Combat]},
	{name: "Kill a Silverfish", infrequency: 8, reactant: ["Pacifist"], tags: [Nether, Overworld, Combat]},
	{name: "Light a Copper Bulb", reactant: ["Pacifist"], infrequency: 8, tags: [Item, Nether, Combat]},
	{name: "Have 2 different wolf breeds as pets", infrequency: 8, antisynergy: ["TameWolf"], tags: [Action, Overworld]},
	{name: "Give a wolf armor", infrequency: 2, antisynergy: ["TameWolf"], tags: [Action, RareBiome, Overworld]},
	{name: "Breed a pair of armadillos", antisynergy: ["BreedAnimals"], infrequency: 2, tags: [Action, RareBiome]},
	{name: "Breed a pair of camels", antisynergy: ["BreedAnimals"], infrequency: 2, tags: [Action, RareBiome]},
	{name: "Duplicate an armor trim",antisynergy: ["ArmorTrims"], infrequency: 4, tags: [Item]},
	{name: "Equip (2-3) different Armor Trims",antisynergy: ["ArmorTrims"], reactant: ["WearArmour"], infrequency: 10, tags: [Item]},
	{name: "Fill a Decorated Pot", antisynergy: ["DecoratedPots"], infrequency: 2, tags: [Item, Overworld]},
	{name: "Fill a Chiseled Bookshelf with written books", antisynergy:["ChiseledBookshelf"], tags: [Item, Overworld]},
	{name: "Fill a Chiseled Bookshelf with enchanted books", antisynergy:["ChiseledBookshelf"], tags: [Item, Overworld]},
	{name: "(16-32) Cherry Logs", infrequency: 4, tags: [Item, RareBiome, Overworld]},
	{name: "Kill an Allay", reactant: ["Pacifist"], infrequency: 8, tags: [Action, RareBiome, Overworld]},
	{name: "Play a Goat Horn",infrequency: 4, tags: [Item, RareBiome, Overworld]},
	{name: "Place (3-5) different non-flower biota in flower pots", tags: [Action]},
	{name: "Grow a Mangrove", tags: [Item, RareBiome, Overworld]},
	{name: "Play 2 different Music Discs at the same time", infrequency: 8, tags: [Item]},
	{name: "Fill a Bundle with Bundles", antisynergy: ["Bundles"], tags: [Item, Overworld]},
	{name: "Bucket of Axolotl", infrequency: 2, tags: [Item, Overworld]},
	{name: "Azalea", tags: [Item, Overworld]},
	{name: "(8-16) Glowberries", tags: [Item, Overworld]},
	{name: "Place a \'Black\' item in a Glow Item Frame", tooltiptext: "Any item with \'Black\' in its name.", tags: [Item, Overworld]},
	{name: "Kill a hostile mob with a stalagmite or stalagtite", reactant: ["Pacifist"], tags: [Item, Combat]},
	{name: "Kill a mob by freezing it.", tooltiptext: "Use powdered snow.", reactant: ["Pacifist"], tags: [RareBiome,Action, Overworld]},
	{name: "Fill a Cauldron with Powdered Snow", infrequency: 2, tags: [RareBiome, Action, Overworld]},
	{name: "(6-7) Different Edible Items", tooltiptext: "Raw and Cooked variants count as one (e.g. Raw Beef and Steak).", tooltipimg: "Goal Tooltip Images/RawAndCooked.jpg", antisynergy: ["EdibleItems"], infrequency: 2, tags: [Item, Overworld]},
	{name: "Beetroot Soup", tags: [Item, Overworld]},
	{name: "Place a Cactus in a Flower Pot", tags: [Action, RareBiome, Overworld]},
	{name: "Detonate a TNT-Minecart", tags: [Action, Overworld]},
	{name: "(10-30) Magma Blocks", tags: [Item]},
	{name: "Damaged Anvil", tags: [Item]},
	{name: "(16-64) Melon Slices", tags: [Item, Overworld]},
	{name: "Get a Skeleton's Bow", reactant: ["Pacifist"], tooltiptext: "Kill Skeletons until you get the rare Bow drop from one.", tags: [Item, Combat]},
	{name: "Diamond Block", antisynergy: ["DiamondBlock"], infrequency: 2, tags: [Item]},
	{name: "(2-3) Lapis Lazuli Blocks", tags: [Item, Overworld]},
	{name: "(3-5) Different Saplings", tooltiptext: "Crimson and Warped Fungi don't count!", tags: [Item, Overworld]},
	{name: "Tame a Wolf", antisynergy: ["TameWolf"], tags: [Action, RareBiome, Overworld]},
	{name: "6 Fire Charges", tags: [Item, Nether, Combat]},
	{name: "(2-3) Magma Cream", tags: [Item, Nether, Combat]},
	{name: "Create an Iron Golem", tags: [Action, Overworld]},
	{name: "Eye of Ender", reactant: ["Pacifist"], antisynergy: ["EyeOfEnder"], tags: [Item, Nether, Combat]},
	{name: "Rabbit Stew", tags: [Item, Overworld]},
	{name: "Potion of Fire Resistance", infrequency: 12, tags: [Item, Nether]}, // no Pacifist reactant and no Combat tag (Blaze Powder), no Overworld tag (Water Bottles), because can be bartered
	{name: "Potion of Healing", infrequency: 12, reactant: ["Pacifist"], tags: [Item, Nether, Overworld, Combat]},
	{name: "Potion of Poison", infrequency: 12, reactant: ["Pacifist"], tags: [Item, Nether, Overworld, Combat]},
	{name: "Potion of Harming", infrequency: 12, reactant: ["Pacifist"], tags: [Item, Nether, Overworld, Combat]},
	{name: "Potion of Regeneration", infrequency: 12, reactant: ["Pacifist"], tags: [Item, Nether, Overworld, Combat]},
	{name: "Potion of Slowness", infrequency: 12, reactant: ["Pacifist"], tags: [Item, Nether, Overworld, Combat]},
	{name: "Potion of Strength", infrequency: 12, reactant: ["Pacifist"], tags: [Item, Nether, Overworld, Combat]},
	{name: "Potion of Swiftness", infrequency: 12, reactant: ["Pacifist"], tags: [Item, Nether, Overworld, Combat]},
	{name: "Potion of Weakness", infrequency: 12, reactant: ["Pacifist"], tags: [Item, Nether, Overworld, Combat]},
	{name: "Potion of Leaping", infrequency: 12, reactant: ["Pacifist"], tags: [Item, Nether, RareBiome, Overworld, Combat]},
	{name: "Potion of Slow Falling", infrequency: 12, reactant: ["Pacifist"], tags: [Item, Nether, Combat, Overworld]},
	{name: "Potion of the Turtle Master", infrequency: 12, reactant: ["Pacifist"], tags: [Item, Nether, Ocean, Overworld, Combat]},
	{name: "Kill yourself with your own arrow", reactant: ["Pacifist"], tags: [Action]},
	{name: "Get a '... whilst trying to escape ...' Death message", tooltiptext: "Example: 'PLAYER' drowned whilst trying to escape a Skeleton.", tags: [Action]},
	{name: "Kill a hostile mob with Gravel", reactant: ["Pacifist"], antisynergy: ["KillFallingBlock"], infrequency: 2, tags: [Action, Combat]},
	{name: "Kill a hostile mob with Sand", reactant: ["Pacifist"], antisynergy: ["KillFallingBlock"], infrequency: 2, tags: [Action, Combat, Overworld]},
	{name: "Put a Carpet on a Llama", tags: [RareBiome, Action, Overworld]},
	{name: "Activate a (4-6)x(4-6) Nether Portal (not counting corners)", tooltiptext: "Width/height of the Obsidian frame, disregarding corners (or in other words, width/height of the—once activated—purple portal area).", tooltipimg: "Goal Tooltip Images/Portal.jpg", tags: [Action, Build, Nether]},
	{name: "(3-10) Obsidian", tags: [Item]},
	{name: "(5-7) Iron Blocks", antisynergy: ["IronBlocks"], infrequency: 2, tags: [Item]},
	{name: "(2-4) Gold Blocks", antisynergy: ["GoldBlocks"], infrequency: 2, tags: [Item]},
	{name: "Daylight Detector", tags: [Item, Overworld, Nether]},
	{name: "Enchanted Golden Sword", tags: [Item]},
	{name: "(8-11) Colours of Wool", antisynergy: ["WoolColour"], infrequency: 4, tags: [Item, Colour, Overworld]},
	{name: "(8-11) Colours of Terracotta", reactant: ["UseFurnace"], antisynergy: ["TerracottaColour"], infrequency: 4, tags: [Item, Colour, Overworld]},
	{name: "(7-10) Colours of Glazed Terracotta", reactant: ["UseFurnace"], antisynergy: ["GlazedColour"], infrequency: 4, tags: [Item, Colour, Overworld]},
	{name: "(7-10) Colours of Concrete", antisynergy: ["ConcreteColour"], infrequency: 4, tags: [Item, Colour, Overworld]},
	{name: "Place (7-10) colours of Beds next to each other", antisynergy: ["BedColour"], infrequency: 4, tags: [Build, Colour, Overworld]},
	{name: "Power a Redstone Lamp", tags: [Action, Overworld]},
	{name: "(8-10) Different Flowers", antisynergy: ["Flowers"], infrequency: 2, tags: [Item, Overworld]},
	{name: "Put a Zombified Piglin in Water", tags: [Action, Nether, Overworld]},
	{name: "Place an Iron, Gold and Diamond block on top of each other", tags: [Build]},
	{name: "Kill a hostile mob with an Anvil", reactant: ["Pacifist"], tags: [Action, Combat]},
	{name: "Level (16-26)", antisynergy: ["Level"], infrequency: 2, tags: [Stat]},
	{name: "(2-3) Different Seeds", tooltiptext: "Any item with \"Seeds\" in the name.", tags: [Item, Overworld]},
	{name: "Wear 4 Different Armour types at the same time",  tooltiptext: "Example: GOLD shoes, LEATHER Trousers, IRON Chestplate and DIAMOND Helmet.", tooltipimg: "Goal Tooltip Images/4Armour.jpg", reactant: ["WearArmour"], tags: [Action]},
	{name: "Fill a Hopper with 320 items", tags: [Action, Item]},
	{name: "(8-16) Red Nether Brick Blocks", reactant: ["UseFurnace"], tags: [Item, Nether]},
	{name: "(16-32) Spectral Arrows", tags: [Item, Nether]},
	{name: "(33-64) Rotten Flesh", antisynergy: ["RotFlesh"], infrequency: 2, tags: [Item]},
	{name: "(16-32) Ink Sacs", antisynergy: ["InkSacs"], infrequency: 2, tags: [Item, Overworld]},
	{name: "(5-9) Slimeballs", tags: [Item, RareBiome, Overworld]},
	{name: "Use a Lead on a Rabbit", tags: [Action, RareBiome, Overworld]},
	{name: "Firework Star", tags: [Item, Overworld]},
	{name: "Hang a mob with a Lead", reactant: ["Pacifist"], tooltiptext: "Suspend a mob in mid air using Fences and a Lead.", tooltipimg: "Goal Tooltip Images/HangingLead.jpg", tags: [Action, RareBiome, Overworld]},
	{name: "Ghast Tear", reactant: ["Pacifist"], tags: [Item, Nether, Combat]},
	{name: "Never use Coal", tooltiptext: "Never use Coal for any crafting recipes or fuel in a Furnace, CAN use Charcoal.", catalyst: ["NeverCoal"], tooltipimg: "Goal Tooltip Images/NoCoal.jpg", tags: [Never]},
	{name: "(32-64) Glowstone Dust", tags: [Item, Nether]},
	{name: "(10-32) Item Frames", tags: [Item]},
	{name: "(3-4) Different Diamond Items", antisynergy: ["DiamondItems"], tooltiptext: "Any item with 'Diamond' in its name (yes, even itself).", tags: [Item]},
	{name: "(2-4) Prismarine Crystals", infrequency: 2, tags: [Item, Ocean, Overworld]},
	{name: "Dig straight down to Bedrock from Sea level (1x1 hole)", tooltiptext: "Sea Level is Y=63, but starting from higher is fine.", tags: [Action, Overworld]},
	{name: "Deplete an Iron Sword", reactant: ["SwordUse"], tooltiptext: "Use an Iron Sword until it breaks, check the 'Items' statistics screen!", tooltipimg: "Goal Tooltip Images/SwordDepelete.jpg", tags: [Action, Stat]},
	{name: "Give a mob a Hat", tags: [Action, Combat]},
	{name: "Heart of the Sea", tags: [Item, Ocean, Overworld]},
	{name: "Phantom Membrane", reactant: ["Pacifist"], tags: [Item, Combat, Overworld]},
	{name: "Add a Marker to a Map", tags: [Action, Overworld]},
	{name: "Water, Lava, Milk and Fish Bucket", antisynergy: ["BucketTypes", "WaterBucket", "LavaBucket", "MilkBucket", "FishBucket"], reactant: ["UseBuckets"], tooltiptext: "Can be any of the types of Fish.", tooltipimg: "Goal Tooltip Images/FishBucket.jpg", tags: [Item, Overworld]},
	{name: "Leash a mob to a Dolphin", tags: [Action, Ocean, RareBiome, Overworld]},
	{name: "(11-15) Dried Kelp Blocks", antisynergy: ["KelpBlocks"], tags: [Item, Ocean, Overworld]},
	{name: "(6-15) Gunpowder", antisynergy: ["Gunpowder"], infrequency: 2, tags: [Item, Combat]},
	{name: "(6-15) Spider Eyes", antisynergy: ["SpiderEye"], infrequency: 2, tags: [Item, Combat, Overworld]},
	{name: "(4-6) Ender Pearls", antisynergy: ["EnderPearl"], infrequency: 2, tags: [Item, Combat]},
	{name: "Enchant an item", antisynergy: ["Enchant"], tags: [Action, Overworld]},
	{name: "Blue Shield with White Flower Charge Pattern", tags: [Item, Overworld]},
	{name: "Tame a Cat", tags: [Action, Village, Overworld]},
	{name: "Breed (5-7) sets of mobs", tooltiptext: "Check the 'General' statistics screen!", antisynergy: ["BreedAnimals"], infrequency: 2, tags: [Action, Stat]},
	{name: "Crouch a distance of (200-400) meters", tooltiptext: "Check the 'General' statistics screen!", antisynergy: ["CrouchDistance"], infrequency: 2, tags: [Action, Stat]},
	{name: "Kill (75-100) mobs", reactant: ["Pacifist"], tooltiptext: "Check the 'General' statistics screen!", antisynergy: ["MobKills"], tags: [Action, Combat, Stat]},
	{name: "(33-64) Seagrass", antisynergy: ["Seagrass"], infrequency: 2, tags: [Item, Ocean, Overworld]},
	{name: "Kill an Iron Golem", reactant: ["Pacifist"], tags: [Action, Overworld]},
	{name: "Kill a mob with an End Crystal", reactant: ["Pacifist"], tags: [Action, Overworld, Nether, Combat]},
	{name: "Never Craft Sticks", tags: [Never, Overworld]}, // Overworld because can't get sticks in the Nether without crafting them
	{name: "Light a Campfire from 10 blocks away", tags: [Action]},
	{name: "Max Scale Map", tooltiptext: "You don't need to complete it, just zoom it out with a Cartography Table.", tags: [Item, Overworld]},
	{name: "Ignite a TNT with a Lectern", tags: [Action, Overworld]},
	{name: "Kill a hostile mob with a Sweet Berry Bush", reactant: ["Pacifist"], tags: [Action, Overworld, Combat, RareBiome]},
	{name: "Get a Pillager's Crossbow", reactant: ["Pacifist"], tooltiptext: "Kill Pillagers until you get a rare Crossbow drop from one.", tags: [Item, Combat, Overworld, RareBiome]},
	{name: "Ominous Banner", reactant: ["Pacifist"], tags: [Item, Combat, Overworld]},
	{name: "Gain a Fox's Trust", tags: [Action, Overworld, RareBiome]},
	{name: "Honey Block", antisynergy: ["Honey"], infrequency: 2, tags: [Action, Overworld]},
	{name: "Honeycomb Block", antisynergy: ["Honeycomb"], infrequency: 2, tags: [Action, Overworld]},
	{name: "Repair an Iron Golem", tags: [Action, Overworld, Village]},
	{name: "Grow a Tree with a Bee Nest attached", tags: [Action, Overworld]},
	{name: "(16-32) Warped Stem", infrequency: 25, tags: [Item, Nether]},
	{name: "(16-32) Stripped Warped Stem", infrequency: 25, tags: [Item, Nether]},
	{name: "(16-32) Warped Hyphae", infrequency: 25, tags: [Item, Nether]},
	{name: "(16-32) Stripped Warped Hyphae", infrequency: 25, tags: [Item, Nether]},
	{name: "(16-32) Warped Planks", infrequency: 25, tags: [Item, Nether]},
	{name: "(16-32) Crimsom Stem", infrequency: 25, tags: [Item, Nether]},
	{name: "(16-32) Stripped Crimsom Stem", infrequency: 25, tags: [Item, Nether]},
	{name: "(16-32) Crimsom Hyphae", infrequency: 25, tags: [Item, Nether]},
	{name: "(16-32) Stripped Crimsom Hyphae", infrequency: 25, tags: [Item, Nether]},
	{name: "(16-32) Crimsom Planks", infrequency: 25, tags: [Item, Nether]},
	{name: "Block of Quartz", tags: [Item, Nether]},
	{name: "(8-16) Amethyst Shards", tags: [Item, Overworld]},
	{name: "(Try to) use a Respawn Anchor in the Overworld", tags: [Action, Nether]},
	{name: "Warped Fungus on a Stick", tags: [Item, Nether]},
	{name: "Convert a Hoglin into a Zoglin", tags: [Action, Nether, Combat]},
	{name: "Ride a Strider", tags: [Action, Nether]},
	{name: "Damage a Strider with Water", tags: [Action, Nether]},
	{name: "(6-15) Bamboo", tags: [Item, Overworld, RareBiome]},
	{name: "Crying Obsidian", tags: [Item]},
	{name: "Kill yourself with an Ender Pearl", tooltiptext: "Need to die to the small fall damage taken from using a Pearl.", tooltipimg: "Goal Tooltip Images/EnderPearl.jpg", reactant: ["Pacifist"], tags: [Action]},
	{name: "Grass Block", tooltiptext: "If you don't have Silk Touch, I know a guy who might pick one up for you...", tooltipimg: "Goal Tooltip Images/GrassBlock.jpg", tags: [Item, Overworld]},
	{name: "Bounce on a Slime Block", tooltiptext: "Get a Slime Block, place it on the ground and give it a good old bouncin' on.", tooltipimg: "Goal Tooltip Images/SlimeBlock.jpg", tags: [Action, Overworld]},
	{name: "Full Gold Armour", tags: [Item]},
	{name: "Brown Wool", tags: [Item, Overworld]},
	{name: "Grow a Huge Nether Fungus", antisynergy: ["GrowFungus"], tags: [Action, Nether]},
	{name: "Put a Chest on a Donkey", tags: [Action, Overworld]},
],

// Hard (3)
[
	{name: "Place and light a candle in a cake", infrequency: 8, tags: [Action, Overworld]},
	{name: "Break a diamond tool", tags: [Action]},
	{name: "\'Caves and Cliffs\' Advancement", infrequency: 16, tags: [Build, Advancement]},
	{name: "\'Eye Spy\' Advancement", infrequency: 3, tags: [Advancement, Overworld, Nether, Action]},
	{name: "\'Zombie Doctor\' Advancement", tags: [Advancement, Overworld, Action]},
	{name: "\'Spooky Scary Skeleton\' Advancement", tags: [Advancement, Nether, Action]},
	{name: "\'Subspace Bubble\' Advancement", tags: [Advancement, Nether, Action]},
	{name: "\'A Throwaway Joke\' Advancement", tags: [Advancement, Action]},
	{name: "\'Minecraft: Trial(s) Edition\' Advancement", tags: [Advancement, Action]},
	{name: "Create an Enchantment requiring level 10+", tags: [Action, Overworld]},
	{name: "Milk a Mooshroom", infrequency: 2, tags: [Action, RareBiome, Overworld]},
	{name: "Shear a Mooshroom", infrequency: 2, tags: [Action, RareBiome, Overworld]},
	{name: "(2-5) Sea Lanterns", tags: [Item, Ocean, Overworld]},
	{name: "Sponge", tooltiptext: "DRY Sponge, not a Wet one", tooltipimg: "Goal Tooltip Images/Sponge.jpg", tags: [Item, Ocean, Overworld]},
	{name: "Listen to a Music Disc", tags: [Item]},
	{name: "(11-14) Different Flowers", antisynergy: ["Flowers"], infrequency: 3, tags: [Item, RareBiome, Overworld]},
	{name: "(2-4) Diamond Blocks", antisynergy: ["DiamondBlock"], infrequency: 2, tags: [Item]},
	{name: "Get a Zombified Piglin's Sword", reactant: ["Pacifist"], tooltiptext: "Kill Zombified Piglins until you get a rare drop from one, it being their Golden Sword.", tooltipimg: "Goal Tooltip Images/GoldenSword.jpg", tags: [Action, Combat, Nether]},
	{name: "Finish by launching Fireworks of (5-10) Different Colours", tags: [Action, Item, Colour, Overworld, Finish]},
	{name: "Nametag an Enderman", tags: [Action, Combat, Overworld]},
	{name: "Finish on top of a Blaze Spawner", tooltiptext: "Be stood on top of a Blaze Spawner at the end of the game.", tags: [Action, Nether, Combat, Finish]},
	{name: "(12-14) Colours of Wool", antisynergy: ["WoolColour"], infrequency: 4, tags: [Item, Colour, Overworld]},
	{name: "(12-14) Colours of Terracotta", reactant: ["UseFurnace"], antisynergy: ["TerracottaColour"], infrequency: 4, tags: [Item, Colour, Overworld]},
	{name: "(11-14) Colours of Glazed Terracotta", reactant: ["UseFurnace"], antisynergy: ["GlazedColour"], infrequency: 4, tags: [Item, Colour, Overworld]},
	{name: "(11-14) Colours of Concrete", antisynergy: ["ConcreteColour"], infrequency: 4, tags: [Item, Colour, Overworld]},
	{name: "Place (11-14) colours of Beds next to each other", antisynergy: ["BedColour"], infrequency: 4, tags: [Build, Colour, Overworld]},
	{name: "Poison a Parrot", reactant: ["Pacifist"], infrequency: 2, tags: [Action, RareBiome, Overworld]},
	{name: "Tame a Parrot", infrequency: 2, tags: [Action, RareBiome, Overworld]},
	{name: "Ice Block on top of a Magma Block", tags: [Item, Build, Overworld]},
	{name: "Level (27-37)", antisynergy: ["Level"], infrequency: 2, tags: [Stat]},
	{name: "Build a (2-4)x(2-4)x(2-4) Ice cube", tooltiptext: "You can choose what shall be the width/length/height.", tooltipimg: "Goal Tooltip Images/IceCube.jpg", tags: [Build, Overworld]},
	{name: "Finish on top of a stairway to Heaven", tooltiptext: "Using Stairs, build up to Y=256 (height limit) and stand on top at the end of the Bingo. (If you need to jump over a block, it's not a finished stairway.)", tooltipimg: "Goal Tooltip Images/FinishStairs.jpg", tags: [Build, Overworld, Finish]},
	{name: "Get a Ghast into the Overworld", tags: [Action, Nether, Overworld]},
	{name: "Enchanted Golden Apple", tags: [Item]},
	{name: "Kill a mob that is wearing Full Iron Armour", reactant: ["Pacifist"], tags: [Action, Combat]},
	{name: "Enchant 5 different items", antisynergy: ["Enchant"], tags: [Action, Overworld]},
	{name: "Conduit", tags: [Item, Ocean, Overworld]},
	{name: "(2-5) types of Dead Coral Blocks", tags: [Item, Ocean, RareBiome, Overworld]},
	{name: "(16-32) Sea Pickles", tags: [Item, Ocean, RareBiome, Overworld]},
	{name: "Get a '... didn't want to live in the same world as ...' Death message", tags: [Action]},
	{name: "Cookie", tags: [Item, Overworld]},
	{name: "Grow a Full Jungle Tree", tags: [Action, RareBiome, Overworld]},
	{name: "(2-10) Prismarine Shards", infrequency: 2, tags: [Item, Ocean, Overworld]},
	{name: "(16-32) Jungle Logs", infrequency: 4, tags: [Item, RareBiome, Overworld]},
	{name: "(11-20) Jungle Wood", infrequency: 4, tags: [Item, RareBiome, Overworld]},
	{name: "(11-20) Stripped Jungle Wood", reactant: ["AxeUse"], infrequency: 4, tags: [Item, RareBiome, Overworld]},
	{name: "(11-20) Stripped Jungle Logs", reactant: ["AxeUse"], infrequency: 4, tags: [Item, RareBiome, Overworld]},
	{name: "(5-7) Different Diamond Items", antisynergy: ["DiamondItems"], tooltiptext: "Any item with 'Diamond' in its name (yes, even itself).", tags: [Item]},
	{name: "Destroy a Monster Spawner", tags: [Action, Combat]},
	{name: "(32-64) Popped Chorus Fruit", tags: [Item, End]},
	{name: "Get a Villager into The End", tags: [Action, End, Village]},
	{name: "(5-16) Dragon's Breath", tags: [Item, Combat, End]},
	{name: "Dragon Egg", tags: [Item, Combat, End]},
	{name: "Complete a full size Map", antisynergy: ["CompleteMap"], tags: [Action, Overworld]},
	{name: "Be killed by a Villager", tooltiptext: "Sometimes you need to DISPENSE some DEFENCE.", tags: [Village, Overworld, Stat, Combat]},
	{name: "Save yourself with a Totem of Undying", tags: [Item, Overworld]},
	{name: "Every type of Sword", infrequency: 2, antisynergy: ["EverySword"], tooltiptext: "Wooden, Gold, Iron, Diamond and yes, even Netherite.", tags: [Item, Nether, Netherite]},
	{name: "Every type of Pickaxe", infrequency: 2, antisynergy: ["EveryPickaxe"], tooltiptext: "Wooden, Gold, Iron, Diamond and yes, even Netherite.", tags: [Item, Nether, Netherite]},
	{name: "Finish by building a Scaffolding tower, then removing it", tooltiptext: "Build a 1x1 Scaffolding Tower from Bedrock to Y=256 (height limit) and then knock it all down as the final goal.", tags: [Build, Overworld, Finish]},
	{name: "Feed a Panda a Cake", tags: [Action, Overworld, RareBiome]},
	{name: "Make two Pandas breed", tags: [Action, Overworld, RareBiome]},
	{name: "Disarm a Pillager", tooltiptext: "Get a Pillager to not be holding any Weapons", tags: [Action, Overworld, Combat, RareBiome]},
	{name: "Stun a Ravager", tags: [Action, Overworld, Combat, Village]},
	{name: "Become Hero of the Village", reactant: ["Pacifist"], tags: [Action, Overworld, Combat, Village]},
	{name: "Gain an Ocelot's Trust", tags: [Action, Overworld, RareBiome]},
	{name: "12 Eyes of Ender", reactant: ["Pacifist"], tooltiptext: "How good is your luck?", tags: [Item, Nether, Combat]},
	{name: "Netherite Ingot", tags: [Item, Nether, Netherite]},
	{name: "Wither Skull", reactant: ["Pacifist"], tags: [Item, Nether, Combat, RareBiome]},
	{name: "Gilded Blackstone", tags: [Item, Nether, RareBiome]},
	{name: "Give a Piglin Brute an Enchanted Axe", tags: [Action, Nether, Combat, RareBiome]},
	{name: "Build a 6x6 Scaffolding n Shape (not counting corners)", tooltiptext: "Width/height of the inside frame, disregarding corners.", tooltipimg: "Goal Tooltip Images/ScaffingN.jpg", tags: [Build, Overworld]},
	{name: "(2-5) Honey Blocks", antisynergy: ["Honey"], infrequency: 2, tags: [Action, Overworld]},
	{name: "(6-15) Honeycomb Blocks", antisynergy: ["Honeycomb"], infrequency: 2, tags: [Action, Overworld]},
	{name: "Kill a Wandering Trader", reactant: ["Pacifist"], tags: [Action, Overworld, Combat]},
	{name: "Throw a Mending Book into Lava", tags: [Action]},
	{name: "Grow a Huge Nether Fungus in the Overworld", antisynergy: ["GrowFungus"], tags: [Action, Overworld, Nether]},
	{name: "(32-64) Dirt, Netherrack and End Stone", tags: [Item, Overworld, Nether, End]},
	{name: "Tame a Mule", tags: [Action, Overworld]},
	{name: "Convert a Carrot on a Stick into a Fishing Rod", tags: [Action, Overworld]},
	{name: "Skull Charge Banner Pattern", tags: [Item, Nether, Combat, RareBiome, Overworld]},
	{name: "Turtle Shell", antisynergy: ["TurtleShell"], tags: [Item, Ocean, Overworld]},
	{name: "Scute", antisynergy: ["TurtleShell"], tags: [Item, Ocean, Overworld]},
],

// Very Hard (4)
[
	{name: "(12-15) Different Potions", tooltiptext: "Splash, Lingering, Enhanced and Extended variants DON'T count!", reactant: ["Pacifist"], tags: [Item, Nether, Combat, Overworld]},
	{name: "Every type of Chestplate", tooltiptext: "Leather, Gold, Chainmail, Iron, Diamond and yes, even Netherite.", tooltipimg: "Goal Tooltip Images/chainmail chest.jpg", tags: [Item, Combat, Netherite]},
	{name: "Any mob head OTHER than a Wither Skeleton's", tooltiptext: "Dragon, Skeleton, Zombie or a Creeper Head. Wither Skeleton skulls do NOT count.", tags: [Item, Combat, Overworld]},
	{name: "Every colour of Dye", reactant: ["UseFurnace"], antisynergy: ["EveryColour"], infrequency: 2, tooltiptext: "Black, Blue, Brown, Cyan, Grey, Green, Light Blue, Light Grey, Lime, Magenta, Orange, Pink, Purple, Red, White and Yellow!", tooltipimg: "Goal Tooltip Images/EveryColourOfDye.png", tags: [Item, Colour, Overworld]},
	{name: "Level 50", antisynergy: ["Level"], infrequency: 2, tags: [Stat]},
	//{name: "Fill a Double Chest with 3456 items", reactant: ["UseChests"], tags: [Item, Action]}, BOOOORRRRRRRINNG AND TOO EASY
	{name: "(16-32) Tipped Arrows", tags: [Item, Nether, Overworld]},
	{name: "Place 1 of each Mineral block on top of each other", tooltiptext: "Coal, Iron, Gold, Diamond, Redstone, Lapis, Emerald, Quartz and Netherite blocks.", tooltipimg: "Goal Tooltip Images/MineralBlocks.jpg", tags: [Item, Build, Overworld, Nether, Netherite]},
	{name: "Sleep in a Woodland Mansion", tags: [Action, RareBiome, Overworld]},
	{name: "(10-32) Mycelium", tags: [Item, RareBiome, Overworld]},
	{name: "5 types of Coral Blocks", tooltiptext: "The alive stuff, not the Dead Coral Blocks.", tooltipimg: "Goal Tooltip Images/CoralBlocks.jpg", tags: [Item, RareBiome, Ocean, Overworld]},
	{name: "(32-64) Blue Ice", tags: [Item, Overworld]},
	{name: "Fully power a Conduit", tags: [Item, Ocean, Build, Overworld]},
	{name: "Every item Diamonds are used to Craft", antisynergy: ["DiamondItems"], tooltiptext: "Block, Axe, Boots, Chestplate, Helmet, Hoe, Leggings, Pickaxe, Shovel, Sword, Enchantment Table, Firework Star and Jukebox.", tags: [Item]},
	{name: "Get a Shulker into the Overworld", tags: [Action, Combat, End, Overworld]},
	{name: "(5-10) Diamond Blocks", antisynergy: ["DiamondBlock"], infrequency: 2, tags: [Item]},
	{name: "Complete a full size Map in the End", antisynergy: ["CompleteMap"], tags: [Action, Overworld, End]},
	{name: "(32-64) Wither Roses", reactant: ["Pacifist"], tags: [Item, Nether, Combat]},
	{name: "Get a Slimeball from a Panda", tags: [Item, Overworld, RareBiome]},
	{name: "2 Blocks of Netherite", tags: [Item, Nether, Netherite]},
	{name: "Full Netherite Armour and Tools", tags: [Item, Nether, Netherite]},
	{name: "Convert a Pig into a Zombified Piglin", tags: [Action, Overworld]},
	{name: "Trident", tags: [Item, Ocean, Combat, Overworld]},
	{name: "Tame a Skeleton Horse", tags: [Action, Overworld]},
	{name: "Make every colour of Parrot dance at the same time", tags: [Action, Overworld, RareBiome]},
	{name: "Place every colour of Bed next to each other", reactant: ["UseFurnace"], antisynergy: ["EveryColour"], infrequency: 2, tooltiptext: "Black, Blue, Brown, Cyan, Grey, Green, Light Blue, Light Grey, Lime, Magenta, Orange, Pink, Purple, Red, White and Yellow!", tooltipimg: "Goal Tooltip Images/EveryBed.jpg", tags: [Action, Colour, Overworld]},
	{name: "Kill an Enderman with only Endermites", tooltiptext: "Don't hurt the Enderman any other way, only with Endermites.", tags: [Action, Combat, End]},
	{name: "Get Regeneration from a Beacon", reactant: ["Pacifist"], tags: [Item, Nether, Overworld, Combat]},
]

];
